In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/HDFCBANK.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/GRASIM.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/WIPRO.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/stock_metadata.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/BPCL.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/INFY.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/LT.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/RELIANCE.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/BRITANNIA.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/INFRATEL.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/HEROMOTOCO.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/HINDUNILVR.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/TATAMOTORS.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/MM.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/HDFC.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/JSWSTEEL.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/TITAN.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/HINDALCO.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/AXISBANK.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/HCLTECH.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/ADANIPORTS.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/GAIL.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/NIFTY50_all.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/BAJAJFINSV.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/BAJFINANCE.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/ICICIBANK.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/ZEEL.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/ASIANPAINT.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/IOC.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/TATASTEEL.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/COALINDIA.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/NESTLEIND.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/DRREDDY.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/ONGC.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/EICHERMOT.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/UPL.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/SUNPHARMA.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/ULTRACEMCO.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/CIPLA.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/SHREECEM.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/VEDL.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/TCS.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/NTPC.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/MARUTI.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/KOTAKBANK.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/ITC.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/BAJAJ-AUTO.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/SBIN.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/INDUSINDBK.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/BHARTIARTL.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/TECHM.csv
/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/POWERGRID.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/NSE Symbols.CSV
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/HDFCBANK.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SASTASUNDR.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/ARVIND.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/NIRAJ.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/BHAGYAPROP.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/MAGMA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/HOTELRUGBY.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/UNITECH.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/KIMS.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/DIXON.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/IPL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PRAJIND.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PAEL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SUVEN.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/WANBURY.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/GRASIM.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/GAL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/METKORE.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/INDOWIND.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SEPOWER.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SAKSOFT.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/KOKUYOCMLN.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/ONWARDTEC.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/GMDCLTD.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/JPOLYINVST.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PENIND.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/JMFINANCIL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/LAOPALA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/JSWHL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PHILIPCARB.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/MERCATOR.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/TRF.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/GTNTEX.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/JKIL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PRAXIS.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/DVL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/MITTAL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SPAL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SPARC.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/BHARATFORG.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/INFOMEDIA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/NITIRAJ.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/WIPRO.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/RPOWER.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/DTIL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/HERANBA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/TATAELXSI.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/OIL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/RTNPOWER.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/JSL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/CMICABLES.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/MSTCLTD.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/JINDALSTEL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/ALPHAGEO.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/LASA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/KALYANI.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/GRANULES.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/AGARIND.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PRABHAT.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/BIRLACABLE.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SUNDARAM.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SMSPHARMA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/ITDC.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/ATUL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/KSB.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/JYOTHYLAB.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/LAKPRE.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/ACE.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/RSWM.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/JCHAC.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/BANKINDIA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/KCP.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/VISHAL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/YAARII.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SHRIRAMCIT.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/INDSWFTLTD.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PRSMJOHNSN.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/GUFICBIO.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/KALYANIFRG.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/RML.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/KUANTUM.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PRAKASH.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/GANGAFORGE.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PROINDIA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/ASAHIINDIA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/AJANTPHARM.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/RHFL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/MAXHEALTH.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/TINPLATE.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/MUNJALAU.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/AIAENG.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/NAHARSPING.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/ORIENTCEM.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SHANTIGEAR.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/WEALTH.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SHAKTIPUMP.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/ATFL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/ANKITMETAL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SSPOWER.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/EQUITASBNK.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/STERTOOLS.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/HFCL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/DIAMONDYD.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SOMICONVEY.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/JAYBARMARU.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SAREGAMA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/ABCAPITAL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PATINTLOG.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/JUBLPHARMA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/ELECON.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SRTRANSFIN.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/RAMCOCEM.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/RGL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/DEEPAKFERT.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/GESHIP.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/LUPIN.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/DLF.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/GMBREW.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PILITA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/GALLANTT.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/CENTUM.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/MCL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/FACT.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/GODREJAGRO.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/VIVIMEDLAB.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SUNDARMHLD.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/ARENTERP.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/DMART.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SUVIDHAA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/TTL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/CHROMATIC.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/APCOTEXIND.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SUTLEJTEX.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/HGS.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/BPCL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PANACHE.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/MARATHON.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/TIJARIA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/TDPOWERSYS.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/LFIC.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/RENUKA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/HAPPSTMNDS.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/BANARBEADS.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/WATERBASE.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/MOTOGENFIN.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/TAINWALCHM.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/MURUDCERA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PPAP.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/INDOSTAR.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PNCINFRA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PATSPINLTD.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/GOCLCORP.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/HEMIPROP.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/COLPAL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/DCMSHRIRAM.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/ARCOTECH.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/APOLLOHOSP.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SIGIND.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/3MINDIA.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/JAYNECOIND.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/UNIENTER.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/PDSMFL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/BGRENERGY.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/EDELWEISS.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/INFY.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/MRPL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/BEL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/EASEMYTRIP.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/SMLISUZU.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/RUSHIL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/DHUNINV.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/TWL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/MMFL.csv
/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/SCRIP/AKG.csv

In [4]:
import pandas as pd
import os
from glob import glob

folder = "/kaggle/input/datasets/rohanrao/nifty50-stock-market-data"

csv_files = glob(os.path.join(folder, "*.csv"))

csv_files = [
    f for f in csv_files
    if "stock_metadata" not in f.lower()
    and "nifty50_all" not in f.lower()
]

dfs = []

for file in csv_files:
    ticker = os.path.basename(file).replace(".csv", "")
    df = pd.read_csv(file)
    df["Symbol"] = ticker
    dfs.append(df)

individual_master = pd.concat(dfs, ignore_index=True)

/tmp/ipykernel_58/3089489587.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  individual_master = pd.concat(dfs, ignore_index=True)

In [5]:
nifty_all = pd.read_csv("/kaggle/input/datasets/rohanrao/nifty50-stock-market-data/NIFTY50_all.csv")

In [6]:
print("Individual Master:", individual_master.shape)
print("NIFTY50_all:", nifty_all.shape)

Individual Master: (235192, 15)
NIFTY50_all: (235192, 15)

In [7]:
print(sorted(individual_master.columns))
print(sorted(nifty_all.columns))

['%Deliverble', 'Close', 'Date', 'Deliverable Volume', 'High', 'Last', 'Low', 'Open', 'Prev Close', 'Series', 'Symbol', 'Trades', 'Turnover', 'VWAP', 'Volume']
['%Deliverble', 'Close', 'Date', 'Deliverable Volume', 'High', 'Last', 'Low', 'Open', 'Prev Close', 'Series', 'Symbol', 'Trades', 'Turnover', 'VWAP', 'Volume']

In [8]:
print(
    "Individual:",
    individual_master["Symbol"].nunique()
)

print(
    "NIFTY50_all:",
    nifty_all["Symbol"].nunique()
)

Individual: 49
NIFTY50_all: 65

In [9]:
individual_master["Date"] = pd.to_datetime(
    individual_master["Date"]
).dt.strftime("%Y-%m-%d")

nifty_all["Date"] = pd.to_datetime(
    nifty_all["Date"]
).dt.strftime("%Y-%m-%d")

In [10]:
ind_keys = set(
    zip(
        individual_master["Symbol"],
        individual_master["Date"]
    )
)

all_keys = set(
    zip(
        nifty_all["Symbol"],
        nifty_all["Date"]
    )
)

In [11]:
print("Rows in Individual:", len(ind_keys))
print("Rows in NIFTY50_all:", len(all_keys))

print("Common Rows:", len(ind_keys & all_keys))
print("Only in Individual:", len(ind_keys - all_keys))
print("Only in NIFTY50_all:", len(all_keys - ind_keys))

Rows in Individual: 235192
Rows in NIFTY50_all: 235192
Common Rows: 202544
Only in Individual: 32648
Only in NIFTY50_all: 32648

In [12]:
only_ind = pd.DataFrame(
    list(ind_keys - all_keys),
    columns=["Symbol", "Date"]
)

only_all = pd.DataFrame(
    list(all_keys - ind_keys),
    columns=["Symbol", "Date"]
)

print(only_ind.head())
print(only_all.head())

       Symbol        Date
0  BHARTIARTL  2002-04-19
1   KOTAKBANK  2002-02-05
2        INFY  2009-05-07
3          MM  2000-08-03
4        VEDL  2002-01-23
       Symbol        Date
0  BAJAUTOFIN  2001-02-08
1  BAJAUTOFIN  2009-10-06
2  BAJAUTOFIN  2006-06-15
3   HEROHONDA  2003-05-27
4         M&M  2018-06-13

In [13]:
print(sorted(individual_master["Symbol"].unique())[:20])

print(sorted(nifty_all["Symbol"].unique())[:20])

['ADANIPORTS', 'ASIANPAINT', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJFINANCE', 'BHARTIARTL', 'BPCL', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'DRREDDY', 'EICHERMOT', 'GAIL', 'GRASIM', 'HCLTECH', 'HDFC', 'HDFCBANK', 'HEROMOTOCO', 'HINDALCO']
['ADANIPORTS', 'ASIANPAINT', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJAUTOFIN', 'BAJFINANCE', 'BHARTI', 'BHARTIARTL', 'BPCL', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'DRREDDY', 'EICHERMOT', 'GAIL', 'GRASIM', 'HCLTECH', 'HDFC', 'HDFCBANK']

In [14]:
print(
    set(individual_master["Symbol"].unique())
    - set(nifty_all["Symbol"].unique())
)

print(
    set(nifty_all["Symbol"].unique())
    - set(individual_master["Symbol"].unique())
)

{'MM'}
{'KOTAKMAH', 'UTIBANK', 'M&M', 'BAJAUTOFIN', 'SESAGOA', 'JSWSTL', 'HEROHONDA', 'BHARTI', 'TELCO', 'HINDLEVER', 'UNIPHOS', 'TISCO', 'ZEETELE', 'SSLT', 'MUNDRAPORT', 'INFOSYSTCH', 'HINDALC0'}

In [15]:
only_ind = pd.DataFrame(
    list(ind_keys - all_keys),
    columns=["Symbol","Date"]
)

only_ind.head(20)

        Symbol        Date
0   BHARTIARTL  2002-04-19
1    KOTAKBANK  2002-02-05
2         INFY  2009-05-07
3           MM  2000-08-03
4         VEDL  2002-01-23
5           MM  2004-06-01
6           MM  2011-04-05
7         VEDL  2000-02-02
8         VEDL  2004-06-10
9           MM  2013-04-04
10          MM  2007-12-28
11  BAJFINANCE  2005-07-20
12  ADANIPORTS  2011-02-16
13          MM  2007-04-26
14    HINDALCO  2007-05-29
15  TATAMOTORS  2003-03-24
16        ZEEL  2005-05-25
17    AXISBANK  2007-07-24
18        INFY  2004-08-11
19    HINDALCO  2000-01-20

In [16]:
symbol_map = {
    "MUNDRAPORT": "ADANIPORTS",
    "BAJAJAUTOFIN": "BAJFINANCE",
    "BHARTI": "BHARTIARTL",
    "HEROHONDA": "HEROMOTOCO",
    "HINDLEVER": "HINDUNILVR",
    "INFOSYSTCH": "INFY",
    "JSWSTL": "JSWSTEEL",
    "KOTAKMAH": "KOTAKBANK",
    "SESAGOA": "VEDL",
    "SSLT": "VEDL",
    "TELCO": "TATAMOTORS",
    "TISCO": "TATASTEEL",
    "UTIBANK": "AXISBANK",
    "ZEETELE": "ZEEL",
    "M&M": "MM"
}

In [17]:
nifty_all["Symbol"] = (
    nifty_all["Symbol"]
    .replace(symbol_map)
)

In [18]:
ind_keys = set(
    zip(
        individual_master["Symbol"],
        pd.to_datetime(individual_master["Date"]).dt.strftime("%Y-%m-%d")
    )
)

all_keys = set(
    zip(
        nifty_all["Symbol"],
        pd.to_datetime(nifty_all["Date"]).dt.strftime("%Y-%m-%d")
    )
)

print("Rows in Individual:", len(ind_keys))
print("Rows in NIFTY50_all:", len(all_keys))

print("Common Rows:", len(ind_keys & all_keys))
print("Only in Individual:", len(ind_keys - all_keys))
print("Only in NIFTY50_all:", len(all_keys - ind_keys))

Rows in Individual: 235192
Rows in NIFTY50_all: 235192
Common Rows: 228233
Only in Individual: 6959
Only in NIFTY50_all: 6959

In [19]:
only_ind = pd.DataFrame(
    list(ind_keys - all_keys),
    columns=["Symbol", "Date"]
)

only_all = pd.DataFrame(
    list(all_keys - ind_keys),
    columns=["Symbol", "Date"]
)

print(only_ind.head(20))
print(only_all.head(20))

        Symbol        Date
0   BAJFINANCE  2002-06-17
1          UPL  2008-07-28
2   BAJFINANCE  2000-08-24
3          UPL  2007-08-20
4   BAJFINANCE  2002-10-18
5     HINDALCO  2006-10-20
6          UPL  2010-02-10
7   BAJFINANCE  2009-04-27
8   BAJFINANCE  2002-06-26
9   BAJFINANCE  2005-07-20
10    HINDALCO  2000-08-18
11         UPL  2011-05-09
12    HINDALCO  2001-01-09
13    HINDALCO  2007-05-29
14         UPL  2012-03-19
15         UPL  2013-07-30
16    HINDALCO  2004-06-22
17    HINDALCO  2000-01-20
18    HINDALCO  2005-07-08
19    HINDALCO  2002-02-25
        Symbol        Date
0   BAJAUTOFIN  2001-02-08
1   BAJAUTOFIN  2009-10-06
2   BAJAUTOFIN  2006-06-15
3   BAJAUTOFIN  2010-01-25
4      UNIPHOS  2006-06-12
5   BAJAUTOFIN  2004-07-09
6     HINDALC0  2001-12-21
7      UNIPHOS  2004-11-25
8      UNIPHOS  2005-06-04
9   BAJAUTOFIN  2006-07-31
10  BAJAUTOFIN  2003-03-17
11    HINDALC0  2002-09-03
12  BAJAUTOFIN  2000-05-09
13  BAJAUTOFIN  2003-06-30
14  BAJAUTOFIN  2005-08-26
15  BAJAUTOFIN  2005-11-29
16  BAJAUTOFIN  2005-01-03
17  BAJAUTOFIN  2004-05-21
18     UNIPHOS  2008-03-26
19     UNIPHOS  2009-02-18

In [20]:
only_ind = pd.DataFrame(
    list(ind_keys - all_keys),
    columns=["Symbol", "Date"]
)

only_all = pd.DataFrame(
    list(all_keys - ind_keys),
    columns=["Symbol", "Date"]
)

print(only_ind["Symbol"].value_counts().head(20))
print()
print(only_all["Symbol"].value_counts().head(20))

Symbol
BAJFINANCE    2611
UPL           2429
HINDALCO      1919
Name: count, dtype: int64

Symbol
BAJAUTOFIN    2611
UNIPHOS       2429
HINDALC0      1919
Name: count, dtype: int64

In [21]:
print(
    set(only_ind["Symbol"])
)

print(
    set(only_all["Symbol"])
)

{'UPL', 'BAJFINANCE', 'HINDALCO'}
{'BAJAUTOFIN', 'UNIPHOS', 'HINDALC0'}

In [22]:
for sym in sorted(
    set(only_ind["Symbol"])
    | set(only_all["Symbol"])
):
    print(sym)

BAJAUTOFIN
BAJFINANCE
HINDALC0
HINDALCO
UNIPHOS
UPL

In [23]:
symbol_map.update({
    "BAJAJAUTOFIN": "BAJFINANCE",
    "UNIPHOS": "UPL",
    "HINDALC0": "HINDALCO"   # zero -> O
})

In [24]:
nifty_all["Symbol"] = nifty_all["Symbol"].replace({
    "BAJAJAUTOFIN": "BAJFINANCE",
    "UNIPHOS": "UPL",
    "HINDALC0": "HINDALCO"
})

In [25]:
ind_keys = set(
    zip(
        individual_master["Symbol"],
        pd.to_datetime(individual_master["Date"]).dt.strftime("%Y-%m-%d")
    )
)

all_keys = set(
    zip(
        nifty_all["Symbol"],
        pd.to_datetime(nifty_all["Date"]).dt.strftime("%Y-%m-%d")
    )
)

print("Common Rows:", len(ind_keys & all_keys))
print("Only in Individual:", len(ind_keys - all_keys))
print("Only in NIFTY50_all:", len(all_keys - ind_keys))

Common Rows: 232581
Only in Individual: 2611
Only in NIFTY50_all: 2611

In [26]:
print(
    nifty_all[nifty_all["Symbol"] == "BAJAJAUTOFIN"].shape
)

print(
    nifty_all[nifty_all["Symbol"] == "BAJFINANCE"].shape
)

(0, 15)
(2624, 15)

In [27]:
only_ind = pd.DataFrame(
    list(ind_keys - all_keys),
    columns=["Symbol", "Date"]
)

only_all = pd.DataFrame(
    list(all_keys - ind_keys),
    columns=["Symbol", "Date"]
)

print(only_ind.head(30))
print()
print(only_all.head(30))

        Symbol        Date
0   BAJFINANCE  2007-05-03
1   BAJFINANCE  2006-04-21
2   BAJFINANCE  2006-12-20
3   BAJFINANCE  2004-08-17
4   BAJFINANCE  2002-06-17
5   BAJFINANCE  2006-01-27
6   BAJFINANCE  2008-07-08
7   BAJFINANCE  2000-08-24
8   BAJFINANCE  2007-09-28
9   BAJFINANCE  2002-03-11
10  BAJFINANCE  2002-10-18
11  BAJFINANCE  2009-12-14
12  BAJFINANCE  2009-04-27
13  BAJFINANCE  2009-03-02
14  BAJFINANCE  2009-05-28
15  BAJFINANCE  2002-06-26
16  BAJFINANCE  2005-07-20
17  BAJFINANCE  2009-04-28
18  BAJFINANCE  2004-12-06
19  BAJFINANCE  2009-04-17
20  BAJFINANCE  2003-12-29
21  BAJFINANCE  2008-03-10
22  BAJFINANCE  2005-03-07
23  BAJFINANCE  2001-04-09
24  BAJFINANCE  2010-06-08
25  BAJFINANCE  2002-10-11
26  BAJFINANCE  2001-12-24
27  BAJFINANCE  2003-09-08
28  BAJFINANCE  2007-04-13
29  BAJFINANCE  2005-11-11

        Symbol        Date
0   BAJAUTOFIN  2001-02-08
1   BAJAUTOFIN  2009-10-06
2   BAJAUTOFIN  2003-12-04
3   BAJAUTOFIN  2006-06-15
4   BAJAUTOFIN  2010-01-25
5   BAJAUTOFIN  2002-04-09
6   BAJAUTOFIN  2009-11-04
7   BAJAUTOFIN  2000-10-19
8   BAJAUTOFIN  2004-09-22
9   BAJAUTOFIN  2008-05-06
10  BAJAUTOFIN  2004-07-09
11  BAJAUTOFIN  2010-03-25
12  BAJAUTOFIN  2005-08-31
13  BAJAUTOFIN  2008-01-23
14  BAJAUTOFIN  2000-03-31
15  BAJAUTOFIN  2002-12-06
16  BAJAUTOFIN  2007-06-04
17  BAJAUTOFIN  2006-07-31
18  BAJAUTOFIN  2003-03-17
19  BAJAUTOFIN  2000-05-09
20  BAJAUTOFIN  2003-06-30
21  BAJAUTOFIN  2005-08-26
22  BAJAUTOFIN  2005-11-29
23  BAJAUTOFIN  2005-01-03
24  BAJAUTOFIN  2004-05-21
25  BAJAUTOFIN  2001-02-07
26  BAJAUTOFIN  2003-06-11
27  BAJAUTOFIN  2002-05-03
28  BAJAUTOFIN  2005-08-10
29  BAJAUTOFIN  2006-01-02

In [28]:
only_ind["Symbol"].value_counts()

Symbol
BAJFINANCE    2611
Name: count, dtype: int64

In [29]:
only_all["Symbol"].value_counts()

Symbol
BAJAUTOFIN    2611
Name: count, dtype: int64

In [30]:
ind_bf = individual_master[
    individual_master["Symbol"] == "BAJFINANCE"
]

all_bf = nifty_all[
    nifty_all["Symbol"] == "BAJFINANCE"
]

print(len(ind_bf))
print(len(all_bf))

5235
2624

In [31]:
print(ind_bf["Date"].min(), ind_bf["Date"].max())
print(all_bf["Date"].min(), all_bf["Date"].max())

2000-01-03 2021-04-30
2010-09-29 2021-04-30

In [32]:
bf_ind = individual_master[
    individual_master["Symbol"] == "BAJFINANCE"
].copy()

bf_all = nifty_all[
    nifty_all["Symbol"] == "BAJFINANCE"
].copy()

In [33]:
missing_keys = (
    ind_keys - all_keys
)

bf_old = (
    individual_master
    .assign(
        Key=lambda x: list(
            zip(
                x["Symbol"],
                pd.to_datetime(x["Date"]).dt.strftime("%Y-%m-%d")
            )
        )
    )
)

bf_old = bf_old[
    bf_old["Key"].isin(missing_keys)
].drop(columns="Key")

In [34]:
nifty_fixed = pd.concat(
    [nifty_all, bf_old],
    ignore_index=True
)

In [35]:
ind_keys = set(
    zip(
        individual_master["Symbol"],
        pd.to_datetime(
            individual_master["Date"]
        ).dt.strftime("%Y-%m-%d")
    )
)

fixed_keys = set(
    zip(
        nifty_fixed["Symbol"],
        pd.to_datetime(
            nifty_fixed["Date"]
        ).dt.strftime("%Y-%m-%d")
    )
)

In [36]:
print("Rows in Individual:", len(ind_keys))
print("Rows in NIFTY_FIXED:", len(fixed_keys))

print()

print("Common Rows:", len(ind_keys & fixed_keys))
print("Only in Individual:", len(ind_keys - fixed_keys))
print("Only in NIFTY_FIXED:", len(fixed_keys - ind_keys))

Rows in Individual: 235192
Rows in NIFTY_FIXED: 237803

Common Rows: 235192
Only in Individual: 0
Only in NIFTY_FIXED: 2611

In [37]:
only_fixed = pd.DataFrame(
    list(fixed_keys - ind_keys),
    columns=["Symbol","Date"]
)

print(only_fixed["Symbol"].value_counts())

Symbol
BAJAUTOFIN    2611
Name: count, dtype: int64

In [38]:
print(
    nifty_fixed[nifty_fixed["Symbol"]=="BAJAJAUTOFIN"].shape
)

print(
    nifty_fixed[nifty_fixed["Symbol"]=="BAJFINANCE"].shape
)

(0, 15)
(5235, 15)

In [39]:
nifty_fixed.to_csv(
    "master_nifty50_fixed.csv",
    index=False
)

In [40]:
nifty_fixed.shape

(237803, 15)

In [41]:
nifty_fixed.columns.tolist()

['Date',
 'Symbol',
 'Series',
 'Prev Close',
 'Open',
 'High',
 'Low',
 'Last',
 'Close',
 'VWAP',
 'Volume',
 'Turnover',
 'Trades',
 'Deliverable Volume',
 '%Deliverble']

In [42]:
nifty_fixed.isnull().sum()

Date                       0
Symbol                     0
Series                     0
Prev Close                 0
Open                       0
High                       0
Low                        0
Last                       0
Close                      0
VWAP                       0
Volume                     0
Turnover                   0
Trades                117459
Deliverable Volume     16523
%Deliverble            16523
dtype: int64

**2nd dataset**

In [43]:
nifty50_v2 = pd.read_csv("/kaggle/input/datasets/stoicstatic/india-stock-data-nse-1990-2020/Datasets/INDEX/NIFTY 50.csv")

nifty50_v2.shape

(7510, 7)

In [44]:
nifty50_v2.columns.tolist()

['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Turnover']

In [45]:
nifty50_v2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7510 entries, 0 to 7509
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      7510 non-null   object
 1   Open      7510 non-null   float64
 2   High      7510 non-null   float64
 3   Low       7510 non-null   float64
 4   Close     7510 non-null   float64
 5   Volume    6097 non-null   float64
 6   Turnover  6097 non-null   float64
dtypes: float64(6), object(1)
memory usage: 410.8+ KB

In [46]:
nifty50_v2.duplicated().sum()

np.int64(0)

In [47]:
missing = pd.DataFrame({
    "Missing": nifty50_v2.isnull().sum(),
    "Percent": (
        nifty50_v2.isnull().sum()
        / len(nifty50_v2)
        * 100
    ).round(2)
})

missing.sort_values(
    "Percent",
    ascending=False
)

          Missing  Percent
Turnover     1413    18.81
Volume       1413    18.81
Date            0     0.00
High            0     0.00
Open            0     0.00
Close           0     0.00
Low             0     0.00

In [48]:
nifty50_v2["Date"] = pd.to_datetime(
    nifty50_v2["Date"]
)

print(
    "Start:",
    nifty50_v2["Date"].min()
)

print(
    "End:",
    nifty50_v2["Date"].max()
)

Start: 1990-07-03 00:00:00
End: 2021-07-01 00:00:00

In [49]:
print(
    nifty_fixed["Date"].min()
)

print(
    nifty_fixed["Date"].max()
)

2000-01-03
2021-04-30

In [50]:
nifty_index = nifty50_v2.copy()

nifty_index.columns = [
    "Date",
    "NIFTY_Open",
    "NIFTY_High",
    "NIFTY_Low",
    "NIFTY_Close",
    "NIFTY_Volume",
    "NIFTY_Turnover"
]

In [51]:
nifty_index["Date"] = pd.to_datetime(
    nifty_index["Date"]
)

nifty_index = nifty_index.sort_values(
    "Date"
).reset_index(drop=True)

In [52]:
nifty_index["NIFTY_Return"] = (
    nifty_index["NIFTY_Close"]
    .pct_change()
)

nifty_index["NIFTY_MA20"] = (
    nifty_index["NIFTY_Close"]
    .rolling(20)
    .mean()
)

nifty_index["NIFTY_MA50"] = (
    nifty_index["NIFTY_Close"]
    .rolling(50)
    .mean()
)

nifty_index["NIFTY_Volatility_20"] = (
    nifty_index["NIFTY_Return"]
    .rolling(20)
    .std()
)

In [53]:
print(nifty_fixed["Date"].dtype)
print(nifty_index["Date"].dtype)

object
datetime64[ns]

In [54]:
nifty_fixed["Date"] = pd.to_datetime(
    nifty_fixed["Date"]
)

nifty_index["Date"] = pd.to_datetime(
    nifty_index["Date"]
)

In [55]:
print(nifty_fixed["Date"].dtype)
print(nifty_index["Date"].dtype)

datetime64[ns]
datetime64[ns]

In [56]:
master_df = nifty_fixed.merge(
    nifty_index,
    on="Date",
    how="left"
)

In [57]:
print(master_df.shape)

print(
    master_df[
        [
            "NIFTY_Close",
            "NIFTY_Return"
        ]
    ].isnull().sum()
)

(237803, 25)
NIFTY_Close     0
NIFTY_Return    0
dtype: int64

In [58]:
master_df.to_csv(
    "master_df.csv",
    index=False
)

In [59]:
master_df['Turnover'] = master_df['Turnover'].fillna(
    master_df['Volume'] * master_df['Close']
)

In [60]:
master_df['Turnover'].isnull().sum()

np.int64(0)

In [61]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237803 entries, 0 to 237802
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Date                 237803 non-null  datetime64[ns]
 1   Symbol               237803 non-null  object
 2   Series               237803 non-null  object
 3   Prev Close           237803 non-null  float64
 4   Open                 237803 non-null  float64
 5   High                 237803 non-null  float64
 6   Low                  237803 non-null  float64
 7   Last                 237803 non-null  float64
 8   Close                237803 non-null  float64
 9   VWAP                 237803 non-null  float64
 10  Volume               237803 non-null  object
 11  Turnover             237803 non-null  float64
 12  Trades               120344 non-null  float64
 13  Deliverable Volume   221280 non-null  float64
 14  %Deliverble          221280 non-null  float64
 15  NIFTY_Open           237803 non-null  float64
 16  NIFTY_High           237803 non-null  float64
 17  NIFTY_Low            237803 non-null  float64
 18  NIFTY_Close          237803 non-null  float64
 19  NIFTY_Volume         237803 non-null  float64
 20  NIFTY_Turnover       237803 non-null  float64
 21  NIFTY_Return         237803 non-null  float64
 22  NIFTY_MA20           237803 non-null  float64
 23  NIFTY_MA50           237803 non-null  float64
 24  NIFTY_Volatility_20  237803 non-null  float64
dtypes: datetime64[ns](1), float64(21), object(3)
memory usage: 45.4+ MB

In [62]:
remaining = (
    master_df['Deliverable Volume'].isna()
    &
    master_df['%Deliverble'].isna()
)

remaining.sum()

np.int64(16523)

In [63]:
missing_stocks = (
    master_df.loc[
        master_df['Deliverable Volume'].isna(),
        'Symbol'
    ]
    .value_counts()
)

print(missing_stocks.head(20))

Symbol
SUNPHARMA     528
HINDALCO      525
ZEEL          519
ICICIBANK     517
HINDUNILVR    515
SBIN          514
RELIANCE      514
TATAMOTORS    514
TITAN         514
TATASTEEL     514
ITC           514
CIPLA         514
VEDL          513
ASIANPAINT    509
MM            509
WIPRO         509
BPCL          509
BRITANNIA     509
AXISBANK      509
DRREDDY       509
Name: count, dtype: int64

In [71]:
master_df["Trades"] = master_df["Trades"].fillna(0)

In [65]:
master_df['DV_Missing'] = (
    master_df['Deliverable Volume']
    .isna()
    .astype(int)
)

In [67]:
master_df['%D_Missing'] = (
    master_df['%Deliverble']
    .isna()
    .astype(int)
)

In [68]:
master_df['%Deliverble'] = (
    master_df.groupby('Symbol')['%Deliverble']
    .transform(
        lambda x: x.fillna(x.median())
    )
)

In [69]:
master_df['Deliverable Volume'] = (
    master_df['Volume']
    * master_df['%Deliverble']
    / 100
)

In [72]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237803 entries, 0 to 237802
Data columns (total 27 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Date                 237803 non-null  datetime64[ns]
 1   Symbol               237803 non-null  object
 2   Series               237803 non-null  object
 3   Prev Close           237803 non-null  float64
 4   Open                 237803 non-null  float64
 5   High                 237803 non-null  float64
 6   Low                  237803 non-null  float64
 7   Last                 237803 non-null  float64
 8   Close                237803 non-null  float64
 9   VWAP                 237803 non-null  float64
 10  Volume               237803 non-null  object
 11  Turnover             237803 non-null  float64
 12  Trades               237803 non-null  float64
 13  Deliverable Volume   237803 non-null  object
 14  %Deliverble          237803 non-null  float64
 15  NIFTY_Open           237803 non-null  float64
 16  NIFTY_High           237803 non-null  float64
 17  NIFTY_Low            237803 non-null  float64
 18  NIFTY_Close          237803 non-null  float64
 19  NIFTY_Volume         237803 non-null  float64
 20  NIFTY_Turnover       237803 non-null  float64
 21  NIFTY_Return         237803 non-null  float64
 22  NIFTY_MA20           237803 non-null  float64
 23  NIFTY_MA50           237803 non-null  float64
 24  NIFTY_Volatility_20  237803 non-null  float64
 25  DV_Missing           237803 non-null  int64
 26  %D_Missing           237803 non-null  int64
dtypes: datetime64[ns](1), float64(20), int64(2), object(4)
memory usage: 49.0+ MB

In [73]:
master_df.to_csv(
    "master_clean_df.csv",
    index=False
)